<?php

defined( 'ABSPATH' ) || exit;

final class PhaseOne_Site_Gifts_Engine {
	private static array $product_cache = array();
	private static array $logged_issues = array();

	public static function eligible_order_total( WC_Order $order ): float {
		$total = 0.0;
		foreach ( $order->get_items( 'line_item' ) as $item ) {
			if ( ! $item instanceof WC_Order_Item_Product || PhaseOne_Site_Gifts_Pricing::is_gift_item( $item ) ) {
				continue;
			}
			$total += max( 0, (float) $item->get_total() );
		}

		return round(
			max( 0, (float) apply_filters( 'phaseone_site_gifts_eligible_total', $total, $order ) ),
			wc_get_price_decimals()
		);
	}

	public static function evaluate_order( WC_Order $order ): array {
		return self::evaluate_total( self::eligible_order_total( $order ) );
	}

	public static function evaluate_total( float $eligible_total ): array {
		$config = PhaseOne_Site_Gifts_Rules::get();
		$available = array();
		foreach ( $config['tiers'] as $tier ) {
			if ( ! empty( $tier['active'] ) && ( (float) $tier['threshold'] <= 0 || (int) $tier['product_id'] <= 0 ) ) {
				self::log_once( 'misconfigured-' . (string) $tier['id'], sprintf( 'Gift rule %s is active but incomplete.', $tier['id'] ) );
			}
		}

		$active_tiers = PhaseOne_Site_Gifts_Rules::active_tiers();
		$product_ids = array_values(
			array_unique(
				array_filter(
					array_map(
						static fn( array $tier ): int => ! empty( $tier['variation_id'] ) ? (int) $tier['variation_id'] : (int) $tier['product_id'],
						$active_tiers
					)
				)
			)
		);
		if ( ! empty( $product_ids ) && function_exists( '_prime_post_caches' ) ) {
			_prime_post_caches( $product_ids, true, true );
		}

		foreach ( $active_tiers as $tier ) {
			$dto = self::available_tier( $tier );
			if ( null !== $dto ) {
				$available[] = $dto;
			}
		}

		$unlocked = array_values(
			array_filter(
				$available,
				static fn( array $tier ): bool => $eligible_total + 0.00001 >= (float) $tier['threshold']
			)
		);

		if ( 'highest' === $config['mode'] && count( $unlocked ) > 1 ) {
			$unlocked = array( end( $unlocked ) );
		}

		$next = null;
		foreach ( $available as $tier ) {
			if ( (float) $tier['threshold'] > $eligible_total ) {
				$next = $tier;
				break;
			}
		}

		$highest_threshold = empty( $available ) ? 0.0 : (float) end( $available )['threshold'];
		$markers = array();
		foreach ( $available as $tier ) {
			$markers[] = array(
				// This value is consumed by React as plain text. Never return the
				// HTML generated by wc_price() through the JSON API.
				'label'    => html_entity_decode(
					wp_strip_all_tags( wc_price( (float) $tier['threshold'], array( 'decimals' => 0 ) ) ),
					ENT_QUOTES,
					get_bloginfo( 'charset' ) ?: 'UTF-8'
				),
				'amount'   => (float) $tier['threshold'],
				'percent'  => $highest_threshold > 0 ? min( 100, round( ( (float) $tier['threshold'] / $highest_threshold ) * 100, 2 ) ) : 0,
				'unlocked' => $eligible_total >= (float) $tier['threshold'],
			);
		}

		return array(
			'mode'             => $config['mode'],
			'eligibleTotal'    => round( $eligible_total, 2 ),
			'eligible_total'   => round( $eligible_total, 2 ),
			'gifts'            => $unlocked,
			'availableTiers'   => $available,
			'available_tiers'  => $available,
			'nextTier'         => $next,
			'next_tier'        => $next,
			'isMaxed'          => ! empty( $available ) && null === $next,
			'is_maxed'         => ! empty( $available ) && null === $next,
			'remaining'        => $next ? round( max( 0, (float) $next['threshold'] - $eligible_total ), 2 ) : 0.0,
			'progressPercent'  => $highest_threshold > 0 ? min( 100, round( ( $eligible_total / $highest_threshold ) * 100, 2 ) ) : 0,
			'progress_percent' => $highest_threshold > 0 ? min( 100, round( ( $eligible_total / $highest_threshold ) * 100, 2 ) ) : 0,
			'markers'          => $markers,
		);
	}

	public static function available_tier( array $tier ): ?array {
		$lookup_id = ! empty( $tier['variation_id'] ) ? (int) $tier['variation_id'] : (int) $tier['product_id'];
		$product = self::product( $lookup_id );

		if ( ! $product instanceof WC_Product || ! $product->exists() ) {
			self::log_once( 'missing-' . $lookup_id, sprintf( 'Gift rule %s references a missing product.', $tier['id'] ) );
			return null;
		}
		if ( ! empty( $tier['variation_id'] )
			&& ( ! $product instanceof WC_Product_Variation || (int) $product->get_parent_id() !== (int) $tier['product_id'] ) ) {
			self::log_once( 'variation-' . $lookup_id, sprintf( 'Gift rule %s references an invalid variation.', $tier['id'] ) );
			return null;
		}
		if ( ! $product->is_purchasable() || ! $product->is_in_stock() ) {
			self::log_once( 'unavailable-' . $lookup_id, sprintf( 'Gift rule %s is unavailable or out of stock.', $tier['id'] ) );
			return null;
		}
		if ( method_exists( $product, 'has_enough_stock' ) && ! $product->has_enough_stock( (int) $tier['quantity'] ) ) {
			self::log_once( 'stock-' . $lookup_id, sprintf( 'Gift rule %s does not have enough stock.', $tier['id'] ) );
			return null;
		}

		$image_id = (int) $product->get_image_id();
		if ( ! $image_id && $product instanceof WC_Product_Variation ) {
			$parent = self::product( (int) $product->get_parent_id() );
			$image_id = $parent instanceof WC_Product ? (int) $parent->get_image_id() : 0;
		}

		$name = '' !== trim( (string) $tier['name'] ) ? (string) $tier['name'] : $product->get_name();

		return array(
			'id'            => (string) $tier['id'],
			'ruleId'        => (string) $tier['id'],
			'rule_id'       => (string) $tier['id'],
			'name'          => $name,
			'shortTitle'    => $name,
			'short_title'   => $name,
			'threshold'     => (float) $tier['threshold'],
			'productId'     => (int) $tier['product_id'],
			'product_id'    => (int) $tier['product_id'],
			'variationId'   => (int) $tier['variation_id'],
			'variation_id'  => (int) $tier['variation_id'],
			'productName'   => $product->get_name(),
			'product_name'  => $product->get_name(),
			'quantity'      => (int) $tier['quantity'],
			'image'         => $image_id ? (string) wp_get_attachment_image_url( $image_id, 'woocommerce_thumbnail' ) : '',
			'isRewardGift'   => true,
			'is_reward_gift' => true,
			'cartKey'       => 'reward:' . (string) $tier['id'],
			'price'         => 0,
		);
	}

	private static function product( int $product_id ) {
		if ( ! array_key_exists( $product_id, self::$product_cache ) ) {
			self::$product_cache[ $product_id ] = wc_get_product( $product_id );
		}
		return self::$product_cache[ $product_id ];
	}

	private static function log_once( string $key, string $message ): void {
		if ( isset( self::$logged_issues[ $key ] ) ) {
			return;
		}
		self::$logged_issues[ $key ] = true;

		$logger = wc_get_logger();
		$logger->warning( $message, array( 'source' => 'phaseone-site-gifts' ) );
	}
}
